package com.deenilm.app.ui.strings

import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalContext
import com.deenilm.app.data.Prefs

/**
 * 4-language UI chrome strings (English/Hindi/Bangla/Urdu), ported from the
 * Deen Ilm web app so the whole app follows the app-language setting.
 * Content translations (Quran/Hadith/Discover) are handled separately.
 */
object UiStrings {
    private val en = mapOf(
        "greeting" to "Assalamu alaikum",
        "nextPrayer" to "Next prayer",
        "todayPrayer" to "Today’s prayers",
        "prayerTimes" to "Prayer times",
        "refreshed" to "Updated",
        "home" to "Home",
        "quran" to "Quran",
        "tracker" to "Tracker",
        "community" to "Community",
        "more" to "More",
        "fajr" to "Fajr",
        "sunrise" to "Sunrise",
        "dhuhr" to "Dhuhr",
        "asr" to "Asr",
        "maghrib" to "Maghrib",
        "isha" to "Isha",
        "loading" to "Loading…",
        "retry" to "Try again",
        "changeLocation" to "Change location",
        "city" to "City",
        "country" to "Country",
        "save" to "Save",
        "searchSurah" to "Search surahs",
        "verses" to "verses",
        "meccan" to "Meccan",
        "medinan" to "Medinan",
        "back" to "Back",
        "playFull" to "Play full surah",
        "pause" to "Pause",
        "reciter" to "Reciter",
        "thisWeek" to "This week",
        "streak" to "day prayer streak",
        "completeDay" to "Complete all five prayers today",
        "noChecks" to "Tap a cell to record a prayer.",
        "posts" to "Posts",
        "questions" to "Questions",
        "newPost" to "New post",
        "newQuestion" to "New question",
        "writeThought" to "Write an Islamic reflection…",
        "askQuestion" to "Write your Islamic question…",
        "publish" to "Publish",
        "emptyPosts" to "No posts yet. Share the first reflection.",
        "emptyQuestions" to "No questions yet. Ask the first one.",
        "like" to "Like",
        "liked" to "Liked",
        "duas" to "Duas",
        "hadith" to "Hadith",
        "settings" to "Settings",
        "morning" to "Morning",
        "evening" to "Evening",
        "beforeSleep" to "Before sleep",
        "afterPrayer" to "After prayer",
        "quranicDua" to "Quranic supplication",
        "hadithToday" to "Hadith of the day",
        "collections" to "Collections",
        "excerpt" to "Selected excerpt",
        "language" to "Language",
        "azanAlarm" to "Azan alarm",
        "azanSound" to "Azan sound",
        "notifications" to "Prayer reminders",
        "preview" to "Preview sound",
        "foregroundOnly" to "Alarm plays while this app remains open.",
        "saved" to "Saved",
        "source" to "Source",
        "noData" to "Data is not available right now.",
        "allSurahs" to "114 surahs",
        "liveSchedule" to "Today’s schedule",
        "tapToMark" to "Tap to record",
        "location" to "Location",
        "read" to "Read",
        "stopAudio" to "Stop audio",
        "openDuas" to "Read a dua",
        "openHadith" to "Read hadith",
        "day" to "day",
        "completed" to "complete",
        "remaining" to "remaining",
        "markPrayer" to "Record prayer",
        "current" to "now",
        "in" to "in",
        "ago" to "ago",
        "fullSurahPlaying" to "Full surah playing",
        "serviceError" to "The service did not return data.",
        "openSettings" to "Open settings",
        "today" to "Today",
        "question" to "Question",
        "post" to "Post",
        "close" to "Close",
        "menu" to "Section",
        "all" to "All",
        "playTranslation" to "Play translation",
        "stopTranslation" to "Stop translation",
        "playAllTranslations" to "Play all translations",
        "stopAllTranslations" to "Stop all translations",
        "speechUnavailable" to "Translation speech is not available on this device.",
        "searchHadith" to "Search hadith",
        "searchHadithHint" to "Try prayer, charity, or mercy",
        "randomHadith" to "New hadith",
        "totalHadiths" to "hadiths",
        "noHadithResults" to "No hadith matched this search.",
        "enterHadithSearch" to "Search hadiths in English.",
        "grade" to "Grade",
        "liveFrom" to "Hadith",
        "collectionsCount" to "Available collections",
        "autoTranslated" to "AI translation",
        "translationUnavailable" to "Auto-translation unavailable—showing English",
        "englishOriginal" to "English",
        "publishedTranslation" to "Published translation",
        "collectionHadiths" to "Hadiths in this collection",
        "backToCollections" to "Back to collections",
        "previousPage" to "Previous page",
        "nextPage" to "Next page",
        "page" to "Page",
        "openHadithNumber" to "Open hadith",
        "topics" to "Topics",
        "browseByTopic" to "Browse by topic",
        "chapters" to "Chapters",
        "chapter" to "Chapter",
        "openChapter" to "Open chapter",
        "backToChapters" to "Back to chapters",
        "hadithRange" to "Hadith range",
        "narrator" to "Narrator",
        "copyHadith" to "Copy hadith",
        "shareHadith" to "Share hadith",
        "copied" to "Copied",
        "topicHadiths" to "Hadiths on this topic",
        "useCurrentLocation" to "Use my current location",
        "detectingLocation" to "Detecting your location…",
        "locationDetected" to "Your current location is saved",
        "locationDenied" to "Location permission was not granted. Your saved place remains in use—you can change it.",
        "locationUnavailable" to "Your location could not be found. Enter a city and country instead.",
        "automaticLocation" to "Auto location",
        "manualLocation" to "By city",
        "defaultLocation" to "Default location",
        "locationHelp" to "Use this device’s location for accurate prayer times.",
        "state" to "State",
        "villageCity" to "Village / city",
        "india" to "India",
        "translationAudioUnavailable" to "A recorded translation for this language is unavailable.",
        "recordedTranslation" to "Recorded translation",
        "qariCount" to "reciters",
        "prayerMethod" to "Karachi · Hanafi calculation",
        "district" to "District",
        "gramPanchayat" to "Gram panchayat",
        "pincode" to "PIN code",
        "findVillage" to "Find exact place",
        "selectVillage" to "Use this place",
        "verifiedPostOffice" to "Location found from PIN",
        "exactLocationHelp" to "Enter the village plus its district, gram panchayat, or six-digit PIN. We verify the place and calculate prayer times from its coordinates.",
        "noLocationMatches" to "No place matched. Add the district, panchayat, or PIN and try again.",
        "locationSearch" to "Searching for the place…",
        "discover" to "Discover",
        "books" to "Books",
        "tasbih" to "Tasbih",
        "dua" to "Dua",
    )

    private val hi = mapOf(
        "greeting" to "अस्सलामु अलैकुम",
        "nextPrayer" to "अगली नमाज़",
        "todayPrayer" to "आज की नमाज़",
        "prayerTimes" to "नमाज़ का समय",
        "refreshed" to "अपडेट",
        "home" to "होम",
        "quran" to "क़ुरआन",
        "tracker" to "ट्रैकर",
        "community" to "कम्युनिटी",
        "more" to "और",
        "fajr" to "फ़ज्र",
        "sunrise" to "सूर्योदय",
        "dhuhr" to "ज़ुहर",
        "asr" to "अस्र",
        "maghrib" to "मग़रिब",
        "isha" to "ईशा",
        "loading" to "लोड हो रहा है…",
        "retry" to "फिर कोशिश करें",
        "changeLocation" to "जगह बदलें",
        "city" to "शहर",
        "country" to "देश",
        "save" to "सेव करें",
        "searchSurah" to "सूरह खोजें",
        "verses" to "आयतें",
        "meccan" to "मक्की",
        "medinan" to "मदनी",
        "back" to "वापस",
        "playFull" to "पूरी सूरह सुनें",
        "pause" to "रोकें",
        "reciter" to "क़ारी",
        "thisWeek" to "इस हफ्ते",
        "streak" to "दिन की लगातार पाबंदी",
        "completeDay" to "आज की पाँचों नमाज़ पूरी करें",
        "noChecks" to "किसी खाने पर टैप करके अपनी नमाज़ दर्ज करें।",
        "posts" to "पोस्ट",
        "questions" to "सवाल",
        "newPost" to "नई पोस्ट",
        "newQuestion" to "नया सवाल",
        "writeThought" to "अपनी इस्लामी बात लिखें…",
        "askQuestion" to "अपना इस्लामी सवाल लिखें…",
        "publish" to "पोस्ट करें",
        "emptyPosts" to "अभी कोई पोस्ट नहीं। पहली बात आप लिखें।",
        "emptyQuestions" to "अभी कोई सवाल नहीं। पहला सवाल आप पूछें।",
        "like" to "पसंद",
        "liked" to "पसंद किया",
        "duas" to "दुआएँ",
        "hadith" to "हदीस",
        "settings" to "सेटिंग्स",
        "morning" to "सुबह",
        "evening" to "शाम",
        "beforeSleep" to "सोने से पहले",
        "afterPrayer" to "नमाज़ के बाद",
        "quranicDua" to "क़ुरआनी दुआ",
        "hadithToday" to "आज की हदीस",
        "collections" to "किताबें",
        "excerpt" to "चुना हुआ अंश",
        "language" to "भाषा",
        "azanAlarm" to "अज़ान अलार्म",
        "azanSound" to "अज़ान की आवाज़",
        "notifications" to "नमाज़ रिमाइंडर",
        "preview" to "आवाज़ सुनें",
        "foregroundOnly" to "अलार्म ऐप खुला रहने पर बजेगा।",
        "saved" to "सेव हो गया",
        "source" to "स्रोत",
        "noData" to "डेटा अभी उपलब्ध नहीं है।",
        "allSurahs" to "114 सूरह",
        "liveSchedule" to "आज का समय",
        "tapToMark" to "दर्ज करने के लिए टैप करें",
        "location" to "जगह",
        "read" to "पढ़ें",
        "stopAudio" to "ऑडियो रोकें",
        "openDuas" to "दुआ पढ़ें",
        "openHadith" to "हदीस पढ़ें",
        "day" to "दिन",
        "completed" to "पूरी",
        "remaining" to "बाकी",
        "markPrayer" to "नमाज़ दर्ज करें",
        "current" to "अभी",
        "in" to "में",
        "ago" to "पहले",
        "fullSurahPlaying" to "पूरी सूरह चल रही है",
        "serviceError" to "सेवा से डेटा नहीं मिला।",
        "openSettings" to "सेटिंग्स खोलें",
        "today" to "आज",
        "question" to "सवाल",
        "post" to "पोस्ट",
        "close" to "बंद करें",
        "menu" to "सेक्शन",
        "all" to "सभी",
        "playTranslation" to "अनुवाद सुनें",
        "stopTranslation" to "अनुवाद रोकें",
        "playAllTranslations" to "सभी अनुवाद सुनें",
        "stopAllTranslations" to "सभी अनुवाद रोकें",
        "speechUnavailable" to "इस डिवाइस पर अनुवाद की आवाज़ उपलब्ध नहीं है।",
        "searchHadith" to "हदीस खोजें",
        "searchHadithHint" to "जैसे नमाज़, दान या रहमत",
        "randomHadith" to "नई हदीस",
        "totalHadiths" to "हदीसें",
        "noHadithResults" to "इस खोज पर कोई हदीस नहीं मिली।",
        "enterHadithSearch" to "हिन्दी हदीसों में खोजें।",
        "grade" to "दर्जा",
        "liveFrom" to "हदीस",
        "collectionsCount" to "उपलब्ध संग्रह",
        "autoTranslated" to "AI अनुवाद",
        "translationUnavailable" to "हिन्दी अनुवाद उपलब्ध नहीं",
        "englishOriginal" to "मूल अंग्रेज़ी",
        "publishedTranslation" to "प्रकाशित अनुवाद",
        "collectionHadiths" to "इस किताब की हदीसें",
        "backToCollections" to "किताबों पर वापस",
        "previousPage" to "पिछला पन्ना",
        "nextPage" to "अगला पन्ना",
        "page" to "पन्ना",
        "openHadithNumber" to "हदीस खोलें",
        "topics" to "विषय",
        "browseByTopic" to "विषय से पढ़ें",
        "chapters" to "अध्याय",
        "chapter" to "अध्याय",
        "openChapter" to "अध्याय खोलें",
        "backToChapters" to "अध्यायों पर वापस",
        "hadithRange" to "हदीस सीमा",
        "narrator" to "रावी",
        "copyHadith" to "हदीस कॉपी करें",
        "shareHadith" to "हदीस शेयर करें",
        "copied" to "कॉपी हो गया",
        "topicHadiths" to "इस विषय की हदीसें",
        "useCurrentLocation" to "मेरी जगह पहचानें",
        "detectingLocation" to "जगह पहचानी जा रही है…",
        "locationDetected" to "आपकी मौजूदा जगह सेव हो गई",
        "locationDenied" to "लोकेशन की अनुमति नहीं मिली। सेव की हुई जगह इस्तेमाल हो रही है—आप इसे बदल सकते हैं।",
        "locationUnavailable" to "जगह नहीं मिल सकी। शहर और देश लिखकर समय देखें।",
        "automaticLocation" to "ऑटो लोकेशन",
        "manualLocation" to "शहर से",
        "defaultLocation" to "डिफ़ॉल्ट जगह",
        "locationHelp" to "सही नमाज़ के समय के लिए डिवाइस की लोकेशन इस्तेमाल करें।",
        "state" to "राज्य",
        "villageCity" to "गाँव / शहर",
        "india" to "भारत",
        "translationAudioUnavailable" to "इस भाषा का रिकॉर्ड किया हुआ अनुवाद उपलब्ध नहीं है।",
        "recordedTranslation" to "रिकॉर्ड किया हुआ अनुवाद",
        "qariCount" to "क़ारी",
        "prayerMethod" to "कराची · हनफ़ी गणना",
        "district" to "ज़िला",
        "gramPanchayat" to "ग्राम पंचायत",
        "pincode" to "पिन कोड",
        "findVillage" to "सही जगह खोजें",
        "selectVillage" to "यह जगह चुनें",
        "verifiedPostOffice" to "PIN से जगह मिली",
        "exactLocationHelp" to "गाँव के साथ ज़िला, ग्राम पंचायत या 6 अंकों का PIN दें। हम जगह की पुष्टि करके उसी के निर्देशांक से नमाज़ का समय निकालेंगे।",
        "noLocationMatches" to "जगह नहीं मिली। ज़िला, पंचायत या PIN जोड़कर फिर कोशिश करें।",
        "locationSearch" to "जगह खोजी जा रही है…",
        "discover" to "डिस्कवर",
        "books" to "किताबें",
        "tasbih" to "तस्बीह",
        "dua" to "दुआ",
    )

    private val bn = mapOf(
        "greeting" to "আসসালামু আলাইকুম",
        "nextPrayer" to "পরবর্তী নামাজ",
        "todayPrayer" to "আজকের নামাজ",
        "prayerTimes" to "নামাজের সময়",
        "refreshed" to "হালনাগাদ",
        "home" to "হোম",
        "quran" to "কুরআন",
        "tracker" to "ট্র্যাকার",
        "community" to "কমিউনিটি",
        "more" to "আরও",
        "fajr" to "ফজর",
        "sunrise" to "সূর্যোদয়",
        "dhuhr" to "যোহর",
        "asr" to "আসর",
        "maghrib" to "মাগরিব",
        "isha" to "ইশা",
        "loading" to "লোড হচ্ছে…",
        "retry" to "আবার চেষ্টা করুন",
        "changeLocation" to "স্থান বদলান",
        "city" to "শহর",
        "country" to "দেশ",
        "save" to "সংরক্ষণ",
        "searchSurah" to "সূরা খুঁজুন",
        "verses" to "আয়াত",
        "meccan" to "মাক্কী",
        "medinan" to "মাদানী",
        "back" to "ফিরে যান",
        "playFull" to "পুরো সূরা শুনুন",
        "pause" to "থামান",
        "reciter" to "ক্বারী",
        "thisWeek" to "এই সপ্তাহ",
        "streak" to "দিনের ধারাবাহিকতা",
        "completeDay" to "আজকের পাঁচ নামাজ পূর্ণ করুন",
        "noChecks" to "নামাজ লিখতে একটি ঘরে ট্যাপ করুন।",
        "posts" to "পোস্ট",
        "questions" to "প্রশ্ন",
        "newPost" to "নতুন পোস্ট",
        "newQuestion" to "নতুন প্রশ্ন",
        "writeThought" to "আপনার ইসলামী ভাবনা লিখুন…",
        "askQuestion" to "আপনার ইসলামী প্রশ্ন লিখুন…",
        "publish" to "প্রকাশ করুন",
        "emptyPosts" to "এখনও কোনো পোস্ট নেই। প্রথমটি লিখুন।",
        "emptyQuestions" to "এখনও কোনো প্রশ্ন নেই। প্রথম প্রশ্ন করুন।",
        "like" to "পছন্দ",
        "liked" to "পছন্দ হয়েছে",
        "duas" to "দোয়া",
        "hadith" to "হাদিস",
        "settings" to "সেটিংস",
        "morning" to "সকাল",
        "evening" to "সন্ধ্যা",
        "beforeSleep" to "ঘুমের আগে",
        "afterPrayer" to "নামাজের পরে",
        "quranicDua" to "কুরআনিক দোয়া",
        "hadithToday" to "আজকের হাদিস",
        "collections" to "সংকলন",
        "excerpt" to "নির্বাচিত অংশ",
        "language" to "ভাষা",
        "azanAlarm" to "আজান অ্যালার্ম",
        "azanSound" to "আজানের ধ্বনি",
        "notifications" to "নামাজ রিমাইন্ডার",
        "preview" to "শুনুন",
        "foregroundOnly" to "অ্যাপ খোলা থাকলে অ্যালার্ম বাজবে।",
        "saved" to "সংরক্ষিত",
        "source" to "উৎস",
        "noData" to "তথ্য এখন পাওয়া যাচ্ছে না।",
        "allSurahs" to "১১৪ সূরা",
        "liveSchedule" to "আজকের সময়",
        "tapToMark" to "লিখতে ট্যাপ করুন",
        "location" to "স্থান",
        "read" to "পড়ুন",
        "stopAudio" to "অডিও থামান",
        "openDuas" to "দোয়া পড়ুন",
        "openHadith" to "হাদিস পড়ুন",
        "day" to "দিন",
        "completed" to "সম্পূর্ণ",
        "remaining" to "বাকি",
        "markPrayer" to "নামাজ লিখুন",
        "current" to "এখন",
        "in" to "পরে",
        "ago" to "আগে",
        "fullSurahPlaying" to "পুরো সূরা চলছে",
        "serviceError" to "সেবা থেকে তথ্য পাওয়া যায়নি।",
        "openSettings" to "সেটিংস খুলুন",
        "today" to "আজ",
        "question" to "প্রশ্ন",
        "post" to "পোস্ট",
        "close" to "বন্ধ",
        "menu" to "বিভাগ",
        "all" to "সব",
        "playTranslation" to "অনুবাদ শুনুন",
        "stopTranslation" to "অনুবাদ থামান",
        "playAllTranslations" to "সব অনুবাদ শুনুন",
        "stopAllTranslations" to "সব অনুবাদ থামান",
        "speechUnavailable" to "এই ডিভাইসে অনুবাদের কণ্ঠস্বর পাওয়া যাচ্ছে না।",
        "searchHadith" to "হাদিস খুঁজুন",
        "searchHadithHint" to "যেমন prayer, charity, mercy",
        "randomHadith" to "নতুন হাদিস",
        "totalHadiths" to "হাদিস",
        "noHadithResults" to "এই অনুসন্ধানে কোনো হাদিস পাওয়া যায়নি।",
        "enterHadithSearch" to "বাংলা শব্দ দিয়ে হাদিস খুঁজুন।",
        "grade" to "মান",
        "liveFrom" to "হাদিস",
        "collectionsCount" to "উপলব্ধ সংকলন",
        "autoTranslated" to "AI অনুবাদ",
        "translationUnavailable" to "স্বয়ংক্রিয় অনুবাদ পাওয়া যায়নি—ইংরেজি দেখানো হচ্ছে",
        "englishOriginal" to "মূল ইংরেজি",
        "publishedTranslation" to "প্রকাশিত অনুবাদ",
        "collectionHadiths" to "এই সংকলনের হাদিস",
        "backToCollections" to "সংকলনে ফিরুন",
        "previousPage" to "আগের পাতা",
        "nextPage" to "পরের পাতা",
        "page" to "পৃষ্ঠা",
        "openHadithNumber" to "হাদিস খুলুন",
        "topics" to "বিষয়",
        "browseByTopic" to "বিষয় অনুযায়ী পড়ুন",
        "chapters" to "অধ্যায়",
        "chapter" to "অধ্যায়",
        "openChapter" to "অধ্যায় খুলুন",
        "backToChapters" to "অধ্যায়ে ফিরুন",
        "hadithRange" to "হাদিসের পরিসর",
        "narrator" to "বর্ণনাকারী",
        "copyHadith" to "হাদিস কপি করুন",
        "shareHadith" to "হাদিস শেয়ার করুন",
        "copied" to "কপি হয়েছে",
        "topicHadiths" to "এই বিষয়ের হাদিস",
        "useCurrentLocation" to "আমার অবস্থান শনাক্ত করুন",
        "detectingLocation" to "অবস্থান শনাক্ত হচ্ছে…",
        "locationDetected" to "আপনার বর্তমান অবস্থান সংরক্ষিত হয়েছে",
        "locationDenied" to "অবস্থানের অনুমতি পাওয়া যায়নি। সংরক্ষিত স্থান ব্যবহার করা হচ্ছে—আপনি এটি বদলাতে পারেন।",
        "locationUnavailable" to "অবস্থান পাওয়া যায়নি। শহর ও দেশ লিখে সময় দেখুন।",
        "automaticLocation" to "স্বয়ংক্রিয় অবস্থান",
        "manualLocation" to "শহর অনুযায়ী",
        "defaultLocation" to "ডিফল্ট স্থান",
        "locationHelp" to "সঠিক নামাজের সময়ের জন্য ডিভাইসের অবস্থান ব্যবহার করুন।",
        "state" to "রাজ্য",
        "villageCity" to "গ্রাম / শহর",
        "india" to "ভারত",
        "translationAudioUnavailable" to "এই ভাষার রেকর্ড করা অনুবাদ পাওয়া যায় না।",
        "recordedTranslation" to "রেকর্ড করা অনুবাদ",
        "qariCount" to "ক্বারী",
        "prayerMethod" to "করাচি · হানাফি গণনা",
        "district" to "জেলা",
        "gramPanchayat" to "গ্রাম পঞ্চায়েত",
        "pincode" to "পিন কোড",
        "findVillage" to "সঠিক স্থান খুঁজুন",
        "selectVillage" to "এই স্থান বেছে নিন",
        "verifiedPostOffice" to "PIN থেকে স্থান পাওয়া গেছে",
        "exactLocationHelp" to "গ্রামের সঙ্গে জেলা, গ্রাম পঞ্চায়েত বা ৬ সংখ্যার PIN দিন। স্থান যাচাই করে সেই স্থানাঙ্কে নামাজের সময় দেখানো হবে।",
        "noLocationMatches" to "স্থান পাওয়া যায়নি। জেলা, পঞ্চায়েত বা PIN যোগ করে আবার চেষ্টা করুন।",
        "locationSearch" to "স্থান খোঁজা হচ্ছে…",
        "discover" to "ডিসকভার",
        "books" to "বই",
        "tasbih" to "তাসবীহ",
        "dua" to "দোয়া",
    )

    private val ur = mapOf(
        "greeting" to "السلام علیکم",
        "nextPrayer" to "اگلی نماز",
        "todayPrayer" to "آج کی نماز",
        "prayerTimes" to "نماز کے اوقات",
        "refreshed" to "تازہ",
        "home" to "ہوم",
        "quran" to "قرآن",
        "tracker" to "ٹریکَر",
        "community" to "کمیونٹی",
        "more" to "مزید",
        "fajr" to "فجر",
        "sunrise" to "طلوع آفتاب",
        "dhuhr" to "ظہر",
        "asr" to "عصر",
        "maghrib" to "مغرب",
        "isha" to "عشاء",
        "loading" to "لوڈ ہو رہا ہے…",
        "retry" to "دوبارہ کوشش",
        "changeLocation" to "جگہ بدلیں",
        "city" to "شہر",
        "country" to "ملک",
        "save" to "محفوظ کریں",
        "searchSurah" to "سورت تلاش کریں",
        "verses" to "آیات",
        "meccan" to "مکی",
        "medinan" to "مدنی",
        "back" to "واپس",
        "playFull" to "پوری سورت سنیں",
        "pause" to "روکیں",
        "reciter" to "قاری",
        "thisWeek" to "اس ہفتے",
        "streak" to "دن کا تسلسل",
        "completeDay" to "آج کی پانچ نمازیں مکمل کریں",
        "noChecks" to "نماز درج کرنے کے لیے خانے پر ٹیپ کریں۔",
        "posts" to "پوسٹس",
        "questions" to "سوالات",
        "newPost" to "نئی پوسٹ",
        "newQuestion" to "نیا سوال",
        "writeThought" to "اپنی اسلامی بات لکھیں…",
        "askQuestion" to "اپنا اسلامی سوال لکھیں…",
        "publish" to "شائع کریں",
        "emptyPosts" to "ابھی کوئی پوسٹ نہیں۔ پہلی بات آپ لکھیں۔",
        "emptyQuestions" to "ابھی کوئی سوال نہیں۔ پہلا سوال آپ کریں۔",
        "like" to "پسند",
        "liked" to "پسند کیا",
        "duas" to "دعائیں",
        "hadith" to "حدیث",
        "settings" to "ترتیبات",
        "morning" to "صبح",
        "evening" to "شام",
        "beforeSleep" to "سونے سے پہلے",
        "afterPrayer" to "نماز کے بعد",
        "quranicDua" to "قرآنی دعا",
        "hadithToday" to "آج کی حدیث",
        "collections" to "کتب",
        "excerpt" to "منتخب اقتباس",
        "language" to "زبان",
        "azanAlarm" to "اذان الارم",
        "azanSound" to "اذان کی آواز",
        "notifications" to "نماز یاددہانی",
        "preview" to "سنیں",
        "foregroundOnly" to "الارم ایپ کھلی ہونے پر بجے گا۔",
        "saved" to "محفوظ ہوگیا",
        "source" to "ماخذ",
        "noData" to "معلومات ابھی دستیاب نہیں۔",
        "allSurahs" to "۱۱۴ سورتیں",
        "liveSchedule" to "آج کے اوقات",
        "tapToMark" to "درج کرنے کے لیے ٹیپ کریں",
        "location" to "جگہ",
        "read" to "پڑھیں",
        "stopAudio" to "آڈیو روکیں",
        "openDuas" to "دعا پڑھیں",
        "openHadith" to "حدیث پڑھیں",
        "day" to "دن",
        "completed" to "مکمل",
        "remaining" to "باقی",
        "markPrayer" to "نماز درج کریں",
        "current" to "ابھی",
        "in" to "میں",
        "ago" to "پہلے",
        "fullSurahPlaying" to "پوری سورت چل رہی ہے",
        "serviceError" to "سروس سے معلومات نہیں ملیں۔",
        "openSettings" to "ترتیبات کھولیں",
        "today" to "آج",
        "question" to "سوال",
        "post" to "پوسٹ",
        "close" to "بند کریں",
        "menu" to "حصہ",
        "all" to "سب",
        "playTranslation" to "ترجمہ سنیں",
        "stopTranslation" to "ترجمہ روکیں",
        "playAllTranslations" to "تمام تراجم سنیں",
        "stopAllTranslations" to "تمام تراجم روکیں",
        "speechUnavailable" to "اس ڈیوائس پر ترجمے کی آواز دستیاب نہیں ہے۔",
        "searchHadith" to "حدیث تلاش کریں",
        "searchHadithHint" to "مثلاً prayer, charity, mercy",
        "randomHadith" to "نئی حدیث",
        "totalHadiths" to "احادیث",
        "noHadithResults" to "اس تلاش پر کوئی حدیث نہیں ملی۔",
        "enterHadithSearch" to "اردو لفظ سے حدیث تلاش کریں۔",
        "grade" to "درجہ",
        "liveFrom" to "حدیث",
        "collectionsCount" to "دستیاب مجموعے",
        "autoTranslated" to "AI ترجمہ",
        "translationUnavailable" to "خودکار ترجمہ دستیاب نہیں—انگریزی دکھائی جا رہی ہے",
        "englishOriginal" to "اصل انگریزی",
        "publishedTranslation" to "شائع شدہ ترجمہ",
        "collectionHadiths" to "اس کتاب کی احادیث",
        "backToCollections" to "کتب پر واپس",
        "previousPage" to "پچھلا صفحہ",
        "nextPage" to "اگلا صفحہ",
        "page" to "صفحہ",
        "openHadithNumber" to "حدیث کھولیں",
        "topics" to "موضوعات",
        "browseByTopic" to "موضوع کے لحاظ سے پڑھیں",
        "chapters" to "ابواب",
        "chapter" to "باب",
        "openChapter" to "باب کھولیں",
        "backToChapters" to "ابواب پر واپس",
        "hadithRange" to "احادیث کی حد",
        "narrator" to "راوی",
        "copyHadith" to "حدیث کاپی کریں",
        "shareHadith" to "حدیث شیئر کریں",
        "copied" to "کاپی ہوگئی",
        "topicHadiths" to "اس موضوع کی احادیث",
        "useCurrentLocation" to "میری جگہ معلوم کریں",
        "detectingLocation" to "جگہ معلوم کی جا رہی ہے…",
        "locationDetected" to "آپ کی موجودہ جگہ محفوظ ہوگئی",
        "locationDenied" to "لوکیشن کی اجازت نہیں ملی۔ محفوظ جگہ استعمال ہو رہی ہے—آپ اسے بدل سکتے ہیں۔",
        "locationUnavailable" to "جگہ نہیں مل سکی۔ شہر اور ملک لکھ کر اوقات دیکھیں۔",
        "automaticLocation" to "خودکار لوکیشن",
        "manualLocation" to "شہر کے مطابق",
        "defaultLocation" to "پہلے سے طے شدہ جگہ",
        "locationHelp" to "درست نماز کے اوقات کے لیے ڈیوائس کی لوکیشن استعمال کریں۔",
        "state" to "ریاست",
        "villageCity" to "گاؤں / شہر",
        "india" to "بھارت",
        "translationAudioUnavailable" to "اس زبان کا ریکارڈ شدہ ترجمہ دستیاب نہیں ہے۔",
        "recordedTranslation" to "ریکارڈ شدہ ترجمہ",
        "qariCount" to "قاری",
        "prayerMethod" to "کراچی · حنفی حساب",
        "district" to "ضلع",
        "gramPanchayat" to "گرام پنچایت",
        "pincode" to "پن کوڈ",
        "findVillage" to "صحیح جگہ تلاش کریں",
        "selectVillage" to "یہ جگہ منتخب کریں",
        "verifiedPostOffice" to "PIN سے جگہ مل گئی",
        "exactLocationHelp" to "گاؤں کے ساتھ ضلع، گرام پنچایت یا 6 ہندسوں کا PIN دیں۔ جگہ کی تصدیق کے بعد اسی کے نقاط سے نماز کا وقت نکالا جائے گا۔",
        "noLocationMatches" to "جگہ نہیں ملی۔ ضلع، پنچایت یا PIN شامل کر کے دوبارہ کوشش کریں۔",
        "locationSearch" to "جگہ تلاش ہو رہی ہے…",
        "discover" to "ڈسکور",
        "books" to "کتابیں",
        "tasbih" to "تسبیح",
        "dua" to "دعا",
    )

    /** Localized string for [key] in [lang]; falls back to English, then the key. */
    fun get(key: String, lang: String): String {
        val map = when (lang) {
            "hi" -> hi
            "bn" -> bn
            "ur" -> ur
            else -> en
        }
        return map[key] ?: en[key] ?: key
    }
}

/** Current app-language UI string for [key] (composable). */
@Composable
fun uiString(key: String): String {
    val context = LocalContext.current
    val prefs = remember { Prefs(context) }
    val lang by prefs.lang.collectAsState(initial = "en")
    return UiStrings.get(key, lang)
}
